//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelInformaton.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Fuel
    {
        public int Id { get; set; }
        [DisplayName("Fuel Type")]
        public string Fuel_type { get; set; }
        public int Price { get; set; }
        [DisplayName("Date Modified")]
        public System.DateTime Data_modified { get; set; }
    }
}
